spring.application.name=daeko
server.port=9090

# Logs
logging.level.org.springframework.web=DEBUG
logging.level.com.groupe9=DEBUG

# Configuration postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/daeko_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS referentiel; CREATE SCHEMA IF NOT EXISTS structure_pedagogique;

# Spring Session
spring.session.jdbc.initialize-schema=always

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always
server.error.include-binding-errors=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
